# Generated by Django 3.0.4 on 2020-04-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200331_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Out for deliver', 'Out for deliver'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
